language: node_js
node_js:
- '12'
install:
- npm install -g gitbook-cli@2.3.2
- git clone https://github.com/miklezzzz/gitbook-standard.git -b ru
script:
- cp -rv docs/Общие\ сведения/ gitbook-standard/docs
- cd gitbook-standard/docs
- gitbook install
- gitbook build
after_script:
- git add ../docs
- git commit -m "travis autocommit"
- git status
- git push https://$GITLOGIN:$GITPASS@github.com/miklezzzz/gitbook-standard.git ru
env:
  global:
  - secure: ExUCtxLh/BMBGFB59gdeY52ch/Uts0pKopYCoIyHiGTMZlubFQlWJMO5XakJ+CBr+3oCMt12tGKmRxvYt5zFPY5ieI7emZNeGeBPXrNt3BgAsdNxRpgfgsY5XgfhTcb9IhUT7P8GhFghhLJtAwC0E7tmCwqEjEJJcWhQR+OnSZzRNWh1cOvj271agq+KRYSXTkmjcU4OoLPgWOXJgs9Yqm7YfAbKFUtdIefmILaw8I1x5GAIDD8r6s/4Kc2ZIpgz4p4DGmzOScTyFcF9G1lIDnrH5KDT0cRMneq63zxEs9MO2u4dRqHnXVyssL8rexo5KRx9fuh80ax1padfPiff/VNZY9y3Ce2S+ZGi9ymIsGnSV9LSbzluQP7h6QgBycVKLQGe19d2ZeszFmkgyrVD2HmTSQZx25hLHtpHo+tNozYzkExb+WPfF7ERGsm5xxxheKaDGa+SKCj4+0Yy2jB8KEFZBgln0AMytosIsEoWp7voSVaqI6zUtd+RcEQNOTSo73s2qI29rg41BOt/jh/xShOqvFDavfjak9SXXouw0X8xCGHsxF7a7Z0onTjydVrDqVHNOjVWy5wQlftILeKPLn5ZgrCmUx/WNObGEv+7gbmVTINS90RTCfvvRdzGSDH+kgniZ5g8Fzl6rj4WqHCrngmBInb3WdylFlgH3qBwYMQ=
  - secure: XjOwwe9sirPabIdkn+Kz1GGNVch3VuNFkLdOZB/GNj/IhMLiiL7zybwHy1ZPC+GDruuM2C2lTNyokoNAbLF+xMFpoJbTc4BEMuuuhn+HCqJ3mSMIn7+69Oq819JCYHOmC7jcvRbU3i2/doGFMknW3UeVUKRuNi/LSCnl2dBdsKdJRrgvKDYgS/Pk+1lEN/ylf2jSyySV3ek+hjcmb1bu6EtvpOWl/QrAJ7mrvI4UrCQLJu+ZTZZ17owAlcn0REGubHkgwf9mmPaDvsJJ8nLcF99XHB1JGReolLzYx8NZhf8aN4GnVgXCM9HapAK5DYoT8ZpI63NJO5ty2ULqTLS3rXtbqqQ67Kd11/1onMO0oE6oCMVdeYGOmZb3yJM3bQRI117bTPMbq6PIMajIUATC8+LB6pQY4p9lrsi1l8hLgySQv62coQz1bR9EMQITqBvE69QntnIHf5yPLS1hrNiVlVH3ONFetG68jRc29BY1oIp4Bq0iPzcTy//K/ZB/xsiYN89HsgGhVzeaQl1EcdjKCdr3XOhpPp50j84zfBhvjq4yAznJ9uR6HDcGcy4kKWotomGIWpz7xz7Wfc+jtI/f+iBxjeZuoQ80uvRorqQl6kJ3dEGDCQe7UAN/UI3h9ivIWILHU2GDSzx81K0tuTEIPvky5m2pfo9WR8PNEZcJrIw=
